### ISSUE TITLE
Hiding symlinks

### ISSUE THREAD

**Issue by sikmir** [afify/sfm-patches#1]
I would like to have some config option to hide symlinks (resolved full name) from files list.
For example, insted of:
`result -> /nix/store/9mnmr2n0kphcw8qmjln1w1vkwwac0k0y-sfm-0.3.1`
show something like (`~` is just to make it different from regular files):
`~result`
Ideally, full symlink name could be shown on bottom status line when actual symlink is currently selected.

**Comment by sikmir** [comment]
Here is what I use:
```diff
diff --git i/sfm.c w/sfm.c
index 3a69586..cea2bc1 100644
--- i/sfm.c
+++ w/sfm.c
@@ -286,6 +286,9 @@ print_info(Pane *pane, char *dirsize)
 {
 	char *sz, *ur, *gr, *dt, *prm;
 
+	char *rez_pth;
+	char lnk_full[MAX_N];
+
 	dt = ecalloc(MAX_DTF, sizeof(char));
 
 	prm = get_fperm(CURSOR(pane).mode);
@@ -306,8 +309,17 @@ print_info(Pane *pane, char *dirsize)
 		}
 	}
 
-	print_status(cstatus, "%02d/%02d %s %s:%s %s %s", pane->hdir,
-		pane->dirc, prm, ur, gr, dt, sz);
+	if (S_ISLNK(CURSOR(pane).mode) != 0) {
+		rez_pth = ecalloc(MAX_P, sizeof(char));
+		if (realpath(CURSOR(pane).name, rez_pth) != NULL) {
+			snprintf(
+				lnk_full, MAX_N, " ->%s", rez_pth);
+		}
+		free(rez_pth);
+	}
+
+	print_status(cstatus, "%02d/%02d %s %s:%s %s %s%s", pane->hdir,
+		pane->dirc, prm, ur, gr, dt, sz, lnk_full);
 
 	free(prm);
 	free(ur);
@@ -320,23 +332,12 @@ static void
 print_row(Pane *pane, size_t entpos, Cpair col)
 {
 	int x, y;
-	char *full_str, *rez_pth;
-	char lnk_full[MAX_N];
+	char *full_str;
 
 	full_str = basename(pane->direntr[entpos].name);
 	x = pane->x_srt;
 	y = entpos - pane->firstrow + 1;
 
-	if (S_ISLNK(pane->direntr[entpos].mode) != 0) {
-		rez_pth = ecalloc(MAX_P, sizeof(char));
-		if (realpath(pane->direntr[entpos].name, rez_pth) != NULL) {
-			snprintf(
-				lnk_full, MAX_N, "%s -> %s", full_str, rez_pth);
-			full_str = lnk_full;
-		}
-		free(rez_pth);
-	}
-
 	printf_tb(x, y, col, "%*.*s", ~hwidth, hwidth, full_str);
 }
 

```
There is no need `~` prefix, since symlinks actually have highlighting other than normal files and folders.

**Comment by afify** [comment]
> Here is what I use:
> ```diff
> diff --git i/sfm.c w/sfm.c
> index 3a69586..cea2bc1 100644
> --- i/sfm.c
> +++ w/sfm.c
> @@ -286,6 +286,9 @@ print_info(Pane *pane, char *dirsize)
>  {
>  	char *sz, *ur, *gr, *dt, *prm;
>  
> +	char *rez_pth;
> +	char lnk_full[MAX_N];
> +
>  	dt = ecalloc(MAX_DTF, sizeof(char));
>  
>  	prm = get_fperm(CURSOR(pane).mode);
> @@ -306,8 +309,17 @@ print_info(Pane *pane, char *dirsize)
>  		}
>  	}
>  
> -	print_status(cstatus, "%02d/%02d %s %s:%s %s %s", pane->hdir,
> -		pane->dirc, prm, ur, gr, dt, sz);
> +	if (S_ISLNK(CURSOR(pane).mode) != 0) {
> +		rez_pth = ecalloc(MAX_P, sizeof(char));
> +		if (realpath(CURSOR(pane).name, rez_pth) != NULL) {
> +			snprintf(
> +				lnk_full, MAX_N, " ->%s", rez_pth);
> +		}
> +		free(rez_pth);
> +	}
> +
> +	print_status(cstatus, "%02d/%02d %s %s:%s %s %s%s", pane->hdir,
> +		pane->dirc, prm, ur, gr, dt, sz, lnk_full);
>  
>  	free(prm);
>  	free(ur);
> @@ -320,23 +332,12 @@ static void
>  print_row(Pane *pane, size_t entpos, Cpair col)
>  {
>  	int x, y;
> -	char *full_str, *rez_pth;
> -	char lnk_full[MAX_N];
> +	char *full_str;
>  
>  	full_str = basename(pane->direntr[entpos].name);
>  	x = pane->x_srt;
>  	y = entpos - pane->firstrow + 1;
>  
> -	if (S_ISLNK(pane->direntr[entpos].mode) != 0) {
> -		rez_pth = ecalloc(MAX_P, sizeof(char));
> -		if (realpath(pane->direntr[entpos].name, rez_pth) != NULL) {
> -			snprintf(
> -				lnk_full, MAX_N, "%s -> %s", full_str, rez_pth);
> -			full_str = lnk_full;
> -		}
> -		free(rez_pth);
> -	}
> -
>  	printf_tb(x, y, col, "%*.*s", ~hwidth, hwidth, full_str);
>  }
>  
> 
> ```
> There is no need `~` prefix, since symlinks actually have highlighting other than normal files and folders.

Looks good, can you add this patch as a diff file.
